package com.group4.www.commands.enums;

public enum CommandType {

    CREATEPERSON,
    CREATETEAM,
    CREATEBUGINBOARD,
    CREATESTORYINBOARD,
    CREATEFEEDBACKINBOARD,
    CREATEBOARD,
    //STOYAN
    CREATEBOARDINTEAM,
    SHOWALLMEMBERS,
    SHOWPERSONACTIVITY,
    //MARIAN
    SHOWALLTEAMS,
    SHOWTEAMACTIVITY,
    ADDMEMBERTOTEAM,
    //MONIKA
    SHOWALLTEAMMEMBERS,
    SHOWALLTEAMBOARDS,
    SHOWBOARDACTIVITY,
    //STOYAN
    ADVANCEBUGSTATUS,
    REVERTBUGSTATUS,
    ADVANCESTORYPRIORITY,
    //MARIAN
    ADVANCEBUGPRIORITY,
    REVERTSTORYPRIORITY,
    REVERTBUGPRIORITY,
    //MONIKA
    ADVANCEBUGSEVERITY,
    REVERTBUGSEVERITY,
    ADVANCESTORYSTATUS,
    //STOYAN
    REVERTSTORYSTATUS,
    ADVANCESTORYSIZE,
    REVERTSTORYSIZE,
    //MARIAN
    ADVANCEFEEDBACKSTATUS,
    REVERTFEEDBACKSTATUS,
    CHANGEFEEDBACKRATING,
    //MONIKA
    ASSIGNTASKTOMEMBER,
    UNASSIGNTASKTOMEMBER,
    ADDCOMMENTTOTASK,
    //STOYAN


}
