package com.group4.www.commands.enums;

import com.group4.www.commands.creations.FilterTasksByTitle;

public enum CommandType {

    CREATEPERSON,
    CREATETEAM,
    CREATEBUGINBOARD,
    CREATESTORYINBOARD,
    CREATEFEEDBACKINBOARD,
    CREATEBOARD,
    CREATEBOARDINTEAM,
    SHOWALLMEMBERS,
    SHOWPERSONACTIVITY,
    SHOWALLTEAMS,
    SHOWTEAMACTIVITY,
    ADDMEMBERTOTEAM,
    SHOWALLTEAMMEMBERS,
    SHOWALLTEAMBOARDS,
    SHOWBOARDACTIVITY,
    CHANGEFEEDBACKRATING,
    ASSIGNTASKTOMEMBER,
    UNASSIGNTASKTOMEMBER,
    ADDCOMMENTTOTASK,
    CHANGEBUGSTATUS,
    CHANGEBUGPRIORITY,
    CHANGEBUGSEVERITY,
    CHANGESTORYSTATUS,
    CHANGESTORYPRIORITY,
    CHANGESTORYSIZE,
    CHANGEFEEDBACKSTATUS,
    FILTERTASKSBYTITLE,
    SORTTASKSBYTITLE,
    FILTERTASKSBYSTATUS,
    FILTERTASKSBYASSIGNEE,
    FILTERTASKSBYSTATUSANDASSIGNEE;
}
