package com.group4.www.commands.enums;

public enum CommandType {

    CREATEPERSON,
    CREATETEAM,
    CREATEBUG,
    CREATESTORY,
    CREATEFEEDBACK,
    CREATEBOARD,
    //STOYAN
    CREATEBOARDINTEAM,
    SHOWALLMEMBERS,
    SHOWPERSONACTIVITY,
    //MARIAN
    SHOWALLTEAM,
    SHOWTEAMACTIVITY,
    ADDMEMBERTOTEAM,
    //MONIKA
    SHOWALLTEAMMEMBERS,
    SHOWALLTEAMBOARDS,
    SHOWBOARDACTIVITY,
    //STOYAN
    ADVANCEBUGSTATUS,
    REVERTBUGSTATUS,
    ADVANCESTORYPRIORITY,
    //MARIAN
    ADVANCEBUGPRIORITY,
    REVERTSTORYPRIORITY,
    REVERTBUGPRIORITY,
    //MONIKA
    ADVANCEBUGSEVERITY,
    REVERTBUGSEVERITY,
    ADVANCESTORYSTATUS,
    //STOYAN
    REVERTSTORYSTATUS,
    ADVANCESTORYSIZE,
    REVERTSTORYSIZE,
    //MARIAN
    ADVANCEFEEDBACKSTATUS,
    REVERTFEEDBACKSTATUS,
    CHANGEFEEDBACKRATING,
    //MONIKA
    ASSIGNTASKTOMEMBER,
    UNASSIGNTASKTOMEMBER,
    ADDCOMMENTTOTASK,
    //STOYAN
    FINDBUG,
    FINDSTORY,
    FINDFEEDBACK,
    //MARIAN
    FINDMEMBER,
    FINDBOARD,
    FINDTEAM;


}
